language: node_js
node_js:
- 7
cache:
- node_modules
deploy:
  provider: heroku
  api_key:
    secure: z/bd83u3NHTXdHWWal+E2kqKWC+hfdRfr4551fnQcHumbOdgTV9ouSwjgTOvt0tl3+zWmkNqiqALvnO/nOyMbnB7P/RkBC3/JhYkc+4Hac+0Y835teW+ewHPi5YhGqA20AmzF+nNrQTkxbXYAtPWTrnQUdCiCUwiabVEKmm8cTiXYm+bNhXidaqHZE/a8E2Lw6a1V2Fsq4T7MXqfrJnnWy42NGR0JaRaRe90WFY4eu40pmOPYEdmRIyA+xQ+Yr2UpP8aUAizeLzlcoinBe5rsGz14BHkLyT8nqleroR76j3KdClbOXMur+cBzoYki0sHK7qQaPCvAb2WQmE2AGzZCN4QGURsyTDhrITKuuyPJgv7ZnuWja+RRmxqbG79RlR9N+xQuVB+UFwDVGfbaxPe4kiH6xyFNSEXgsBoyXOeYyGg1L1IKN8rAaOPPHJK9M5C+VkKnZYn3BWW4vauXelB8T0KGWS2EmoV6L5YMzBrsMHtO1sYJitYbStCFNp2vOWnvrIZI54zGCs9LRIlgw5/ORZlnPauxS2E5slcVcGYs3N7S5KO9Q/+qNhHtNlKOYB/ky9es/lGod+9NPo9Z89iza+rkgZqkuZF7V0tmvdkOXjHVkQR40Z0ofuJrDfsg3TtkW3go1MkXAN8MzMkn2ADxhOBenyquIeoQSupA4rQbTw=
  app: cisc3140
  on:
    repo: asher23/cisc3140